### ISSUE TITLE
Addon Compartment mouseover text error

### ISSUE THREAD

**Issue by LvWind** [belazor-wow/ItemUpgradeTip#39]
### Description

Addon Compartment mouseover crash.
and my local is zhCN

### World of Warcraft Flavor

Retail (Default)

### ItemUpgradeTip Version

3.5.1

### Tested with only ItemUpgradeTip

Yes

### Reproduction Steps

1.Open Addon Compartment
2.Mouseover 'ItemUpgradeTip'
3.bugsack collected

### Lua Error

6x ItemUpgradeTip/ItemUpgradeTip.lua:170: attempt to call method 'SetColorAddonBlue' (a nil value)
[string "@ItemUpgradeTip/ItemUpgradeTip.lua"]:170: in function `?'
[string "@Blizzard_Minimap/Mainline/AddonCompartment.lua"]:93: in function <...ddOns/Blizzard_Minimap/Mainline/AddonCompartment.lua:88>
[string "@Blizzard_Minimap/Mainline/AddonCompartment.lua"]:103: in function <...ddOns/Blizzard_Minimap/Mainline/AddonCompartment.lua:102>
[string "@Blizzard_Menu/Menu.lua"]:707: in function `onEnter'
[string "@Blizzard_Menu/Menu.lua"]:729: in function `HandleOnEnter'
[string "@Blizzard_Menu/Menu.lua"]:2111: in function `EnterFrame'
[string "@Blizzard_Menu/Menu.lua"]:2176: in function <Blizzard_Menu/Menu.lua:2175>

Locals:
_ = "ItemUpgradeTip"
menuButtonFrame = Button {
 includeInLayout = true
 skipLayoutOnShow = true
 frameTemplateOrFrameType = "Button"
}
(*temporary) = GameTooltip {
 ItemTooltip = Frame {
 }
 AllTheThingsOnTooltipClearedHook = true
 shadow = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 windInspectLoaded = false
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 __windShadow = 1
 numMoneyFrames = 2
 PixelSnapDisabled = true
 petIcon = Texture {
 }
 supportsDataRefresh = true
 CIMI_tooltipWritten = false
 factionFrame = Texture {
 }
 shouldRefreshData = false
 waitingForData = false
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.062000
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
(*temporary) = "左键点击"
(*temporary) = " "
(*temporary) = nil
(*temporary) = "启用ItemUpgradeTip界面"
(*temporary) = "attempt to call method 'SetColorAddonBlue' (a nil value)"
AddOnFolderName = "ItemUpgradeTip"
L = <table> {
 LEFT_CLICK_DESC = "启用ItemUpgradeTip界面"
 VALORSTONE_CREST_UPGRADES = "神勇石/纹章-升级"
 MODIFIER_KEY = "快捷键"
 REQUIRED_ITEM = "需要物品"
 RIGHT_CLICK = "右键点击"
 UPGRADE_TRACK_CHAMPION = "勇士"
 MYTHICPLUS_TITLE = "ItemUpgradeTip - 史诗+"
 MODIFIER_KEY_DESC = "如果启用，则必须按住此键才能启用鼠标提示整合"
 FLIGHTSTONE_CREST_UPGRADES = "飞珑石/纹章-升级"
 CURRENCY_REMAINING_AFTER_UPGRADING = "升级后剩余货币:"
 BOSS = "首领"
 LFR = "随机"
 DRAKE_CRESTS = "幼龙纹章"
 AUTHOR = "作者"
 CONQUEST_UPGRADES = "征服点数"
 COMPACT_TOOLTIPS_DESC = "如果启用，兼容的鼠标提示将使用更简约的格式，而不是显示完整的信息。"
 RAID_TITLE = "ItemUpgradeTip - 团队副本"
 DRAKE_CRESTS_SHORT = "幼龙"
 BUG_REPORT_SUGGEST = "上报问题 / 功能建议"
 FLIGHTSTONES = "飞珑石"
 ASPECT_CRESTS_SHORT = "守护巨龙"
 X_RARE = "%d (稀有)"
 UPGRADE_TRACKS_TITLE = "ItemUpgradeTip - 升级追踪"
 HEROIC = "英雄"
 MAX_UPGRADE_X = "升满等级 (%d)："
 ANIMA_UPGRADES = "心能升级"
 WYRM_CRESTS_SHORT = "魔龙"
 NEXT_UPGRADE_X = "下个等级 (%d)："
 INFO = "信息"
 DISABLED_INTEGRATIONS = "选择需要禁用的功能"
 CARVED_CRESTS = "蚀刻纹章"
 CREST_TYPE = "纹章种类"
 UPGRADE_LEVEL_X_Y = "提升等级: %d / %d"
 VALORSTONES = "神勇石"
 CRAFTING_TITLE = "ItemUpgradeTip - 制造"
 BUG_REPORT_SUGGEST_TOOLTIP = "在Github上报告问题及提出建议"
 LOOT_DROPS = "拾取掉落"
 VERSION = "版本"
 ITEM_CAN_BE_UPGRADED_TO_MAX = "物品可以升级到满级！"
 CRAFTING = "制造"
 X_UPGRADES = "%s 升级"
 CURRENCY_NEEDED_FOR_MAX = "满级所需货币:"
 BOSS_X = "首领 #%s"
 GILDED_CRESTS_SHORT = "鎏金"
 UPGRADE_TRACK_VETERAN = "老兵"
 GILDED_CRESTS = "鎏金纹章"
 RUNED_CRESTS_SHORT = "符文"
 WEATHERED_CRESTS = "风化纹章"
 INFO_TITLE = "ItemUpgradeTip - 信息"
 CARVED_CRESTS_SHORT = "蚀刻"
 HONOR_UPGRADES = "荣誉点数"
 WEATHERED_CRESTS_SHORT = "风化"
 KEY_LEVEL = "钥石等级"
 RUNED_CRESTS = "符文纹章"
 RIGHT_CLICK_DESC = "启用设置"
 WHELP_CRESTS_SHORT = "雏龙"
 UPGRADE_TRACK_MYTH = "神話"
 LEFT_CLICK = "左键点击"
 RANK = "阶级"
 UPGRADE_TRACK_AWAKENED = "觉醒"
 CONTACT = "联系"
 COST_TO_UPGRADE_TO_MAX = "升到满级:"
 UPGRADE_TRACK_HERO = "英雄"
 ITEM_LEVEL = "物品等级"
 UPGRADE_TRACK_ADVENTURER = "冒险者"
 VAULT_REWARD = "宝库奖励"
 ITEM_UPGRADED_TO_MAX = "物品已升到最大等级！"
 COMPACT_TOOLTIPS = "精简提示"
 MYTHIC = "史诗"
 ASPECT_CRESTS = "守护巨龙纹章"
 UPGRADE_TRACKS = "升级追踪"
 HEIRLOOM_UPGRADES = "传家宝升级"
 MYTHICPLUS = "史诗+"
 NORMAL = "普通"
 RAID = "团队副本"
 WYRM_CRESTS = "魔龙纹章"

**Comment by filliph** [comment]
Yeah I've had other reports of this, I'll make some changes in the coming days. Thanks!
