### ISSUE TITLE
Feature request: option to turn off "cost to upgrade to max level".

### ISSUE THREAD

**Issue by TheRealUncleFrank** [belazor-wow/ItemUpgradeTip#42]
### Is your feature request related to a problem? Please describe.

Not a problem.

### Describe the solution you'd like

Option to turn off / disable "cost to upgrade to max level".
I only want to see cost for next level.
With other addons also adding info to the tooltip, such as All The Things, Pawn, a few others, tooltips are getting very, very long. Freeing up the extra 4-5 rows "cost to upgrade to max" uses, would help to keep things a bit more readable.

**Comment by filliph** [comment]
Have you tried the compact tooltip option? 😄

I'm not opposed to adding the option, but the compact tooltip option might work better for you 🙂

**Comment by TheRealUncleFrank** [comment]
Somehow missed that option. Yes, that works great.
